id: 91423f06-7ed8-4947-89e7-62d82d9486d9
version: 3
vcShouldKeepItemLegacyProdMachine: false
name: LoopingExample
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 382569ff-8862-4d4a-8073-1f6234660172
    type: start
    task:
      id: 382569ff-8862-4d4a-8073-1f6234660172
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: dcef9282-6b52-43b6-8cf2-77fa472e89c3
    type: playbook
    task:
      id: dcef9282-6b52-43b6-8cf2-77fa472e89c3
      version: -1
      name: LoopedPrintingPlaybook
      playbookName: LoopedPrintingPlaybook
      type: playbook
      iscommand: false
      brand: ""
    scriptarguments:
      name:
        simple: ${Names}
    separatecontext: true
    loop:
      iscommand: false
      exitCondition: ""
      wait: 1
      max: 100
      forEach: true
    view: |-
      {
        "position": {
          "x": 450,
          "y": 540
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "2":
    id: "2"
    taskid: b0c9ada3-f313-4cc3-8588-1ae52110f99d
    type: regular
    task:
      id: b0c9ada3-f313-4cc3-8588-1ae52110f99d
      version: -1
      name: Set Raw Names
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      append: {}
      key:
        simple: RawNames
      stringify: {}
      value:
        simple: Alice,Bob,Eve
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "3":
    id: "3"
    taskid: 9fc1c71a-0d9e-4c53-8891-bceb90a87c10
    type: regular
    task:
      id: 9fc1c71a-0d9e-4c53-8891-bceb90a87c10
      version: -1
      name: Create Name Array
      description: Set a value in context under the key you entered.
      scriptName: Set
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    scriptarguments:
      append: {}
      key:
        simple: Names
      stringify: {}
      value:
        complex:
          root: RawNames
          transformers:
          - operator: split
            args:
              delimiter:
                value:
                  simple: ','
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 360
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 585,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
