id: 592539d6-6c99-422b-8227-a6b46eb00fc7
version: 2
vcShouldKeepItemLegacyProdMachine: false
name: LoopedPrintingPlaybook
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 54151480-d48c-47f1-8fcb-5f5b02b19e81
    type: start
    task:
      id: 54151480-d48c-47f1-8fcb-5f5b02b19e81
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
  "1":
    id: "1"
    taskid: 44de579b-1d4d-4d0b-8433-ef821c74475d
    type: regular
    task:
      id: 44de579b-1d4d-4d0b-8433-ef821c74475d
      version: -1
      name: Print
      description: Prints text to war room (Markdown supported)
      scriptName: Print
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      value:
        simple: Hello ${inputs.name}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 275,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
inputs:
- key: name
  value: {}
  required: false
  description: The name of the person to greet.
  playbookInputQuery: null
outputs: []
